/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_helloanotherjni_TestThirdSo */

#ifndef _Included_com_example_helloanotherjni_TestThirdSo
#define _Included_com_example_helloanotherjni_TestThirdSo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_helloanotherjni_TestThirdSo
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_helloanotherjni_TestThirdSo_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
